qavajs/steps-wdio

LICENSE, README.md, docs/action_steps.md, docs/memory_steps.md, docs/parameter_types.md, docs/validation_steps.md, docs/wait_steps.md, package.json, src/actions.ts, src/memory.ts, src/parameterTypeTransformer.ts, src/types.ts, src/validations.ts, src/waits.ts
added new wait and validation steps
added corresponding docs
=> added new wait and validation steps

README.md, index.js, package.json, src/actions.ts, src/conditionWait.ts, src/cookies.ts, src/localSessionStorage.ts, src/types.ts, test/conditionWait.spec.ts
added select option step
added cookie steps
added local/session storage steps
=> added more steps

.github/workflows/npm-publish.yml, .npmignore, README.md, package-lock.json, package.json, src/memory.ts, src/validations.ts
added page title steps
added current url steps
added collection steps
=> added page title, current url and collection steps

CHANGELOG.md, src/waits.ts, test-e2e/apps/waits.html, test-e2e/features/waits.feature
- added I wait until current url step
- added I wait until page title step
=> - added I wait until current url/tittle steps

.github/workflows/pull-request.yml, package-lock.json, package.json, test-e2e/features/actions.feature, test-e2e/features/validations.feature
updated test:e2e command to support cli 0.0.17
added windows pipeline
=> updated test:e2e command to support cli 0.0.17

CHANGELOG.md, package-lock.json, package.json, src/actions.ts, src/conditionWait.ts, src/hooks.ts, src/memory.ts, src/mobile.ts, src/transformers.ts, src/validations.ts, src/waits.ts, test-e2e/apps/actions.html, test-e2e/features/actions.feature, test-e2e/page_object/index.ts, test-e2e/step-definitions/index.ts, test/conditionWait.spec.ts
=> updated po to support ignoreHierarchy

CHANGELOG.md, package-lock.json, package.json, test/utilsImport.spec.ts, tsconfig.json, utils.d.ts, utils.js
=> removed po dependency

CHANGELOG.md, README.md, index.js, package-lock.json, package.json, src/cookies.ts, src/hooks.ts, src/intercept.ts, src/localSessionStorage.ts, src/utils.ts, test-e2e/apps/storage.html, test-e2e/features/intercept.feature, test-e2e/features/storage.feature, test-e2e/page_object/index.ts, test-e2e/support/server.ts, test-e2e/webui.ts
added _I force click_ step
fixed cookie and local storage steps
=> added network interceptor steps

.github/workflows/pull-request.yml, CHANGELOG.md, index.js, package-lock.json, package.json, src/actions.ts, src/hooks.ts, src/multiBrowser.ts, test-e2e/features/actions.feature, test-e2e/features/execute.feature, test-e2e/features/multiBrowser.feature, test-e2e/features/waits.feature
added steps to work with multiple browser contexts
=> added multi browser step

CHANGELOG.md, package-lock.json, package.json, src/hooks.ts, src/mobile.ts, test-e2e/webui.ts
- :rocket: added _I push {string} file as {string}_ step
- :rocket: added _I pull {string} file as {string}_ step
- :rocket: made hooks named
=> Add pull/push file to device steps

.github/pull_request_template.md, CHANGELOG.md, package-lock.json, package.json, src/types.ts, src/valueWait.ts, src/waits.ts, test-e2e/features/waits.feature, test-e2e/webui.ts, test/valueWait.spec.ts
added _match_ value wait
added _I wait until {string} css property of {string} {playwrightValueWait} {string}( ){playwrightTimeout}_ step
=> added _match_ value wait and _css wait_ step

CHANGELOG.md, package-lock.json, package.json
=> release 0.42.0

CHANGELOG.md, package-lock.json, package.json, src/hooks.ts, src/multiBrowser.ts, src/transformers.ts, test-e2e/step-definitions/index.ts, tsconfig.json
=> activated po logger

CHANGELOG.md, package-lock.json, package.json, src/hooks.ts, src/mock.ts, src/multiBrowser.ts, src/validations.ts, src/waits.ts, test-e2e/step-definitions/index.ts, tsconfig.json
added present validation before value wait to prevent promise rejection without reason error
=> added present validation before value wait to prevent promise rejection without reason error

package-lock.json, package.json
=> updated validation dependency

CHANGELOG.md, package-lock.json, package.json, test-e2e/features/actions.feature
=> updated wdio version

CHANGELOG.md, package-lock.json, package.json
updated webdriverio dependency
=> updated webdriverio dependency

CHANGELOG.md, README.md, package-lock.json, package.json, src/hooks.ts, src/utils.ts
top level _config.screenshot_ property was removed. Define this property in _config.browser.screenshot_
=> top level _config.screenshot_ property was removed

.github/workflows/npm-publish.yml, .github/workflows/pull-request.yml, CHANGELOG.md, src/validations.ts, src/waits.ts, test-e2e/features/validations.feature, test-e2e/features/waits.feature, test-e2e/webui.ts
=> added value wait and validation

CHANGELOG.md, package-lock.json, package.json
=> release 0.49.0

.github/workflows/npm-publish.yml, CHANGELOG.md, package-lock.json, package.json
=> Breaking change: moved _@qavajs/validation_ to peer dependencies

CHANGELOG.md, index.d.ts, package-lock.json, package.json, src/IQavajsWdioConfig.ts, src/defaultTimeouts.ts, src/waits.ts, test-e2e/apps/waits.html, test-e2e/features/waits.feature, test-e2e/page_object/index.ts
=> Click until text

CHANGELOG.md, package-lock.json, package.json, po.d.ts, po.js, src/actions.ts, src/memory.ts, src/mobile.ts, src/mock.ts, src/transformers.ts, src/validations.ts, src/waits.ts, test-e2e/page_object/index.ts, test-e2e/webui.ts, test/poImport.spec.ts, tsconfig.json
=> include page objects into step bundle

CHANGELOG.md, package-lock.json, package.json, src/memory.ts, src/validations.ts
=> fixed issue with saving data from collection

.github/workflows/npm-publish-v1.yaml, CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, test-e2e/features/pageObject.feature, test-e2e/features/validations.feature, test-e2e/page_object/index.ts, test-e2e/step-definitions/index.ts
=> added page object tests

CHANGELOG.md, src/types.ts, test-e2e/features/pageObject.feature, test-e2e/step-definitions/index.ts
=> add memory processor to playwrightLocator parameter type

.github/workflows/pull-request.yml, CHANGELOG.md, index.js, package-lock.json, package.json, src/hooks.ts, test-e2e/import.ts
:beetle: fixed index import
:beetle: fixed `reuseSession` flag
---
=> fixed index import and reuse session flag

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, test-e2e/features/pageObject.feature, test-e2e/page_object/index.ts
=> added `locator.as` method to define top level components (like pages)

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, src/validations.ts
=> fixed resolving empty selector logic for collections

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts
=> added capability to pass object as `pageObject` property

CHANGELOG.md, package-lock.json, package.json, src/actions.ts, src/memory.ts, test-e2e/webui.ts
fixed issue in `switch to frame by element` step
---
=> fixed issue in `save attribute` step

CHANGELOG.md, package-lock.json, package.json, src/execute.ts, test-e2e/features/execute.feature
=> improved readability of execute steps

CHANGELOG.md, package-lock.json, package.json, src/conditionWait.ts, src/validations.ts, test-e2e/features/pollValidation.feature, test-e2e/page_object/index.ts
=> pass corresponding timeout into condition waits

.github/workflows/pull-request.yml, CHANGELOG.md, index.js, package-lock.json, package.json, src/actions.ts, src/dialog.ts, src/execute.ts, src/intercept.ts, src/validations.ts, test-e2e/features/actions.feature, test-e2e/features/dialog.feature, test-e2e/features/execute.feature, test-e2e/features/intercept.feature, test-e2e/webui.ts
fixed bidi execute script steps
---
=> added bidi step `I will wait for alert/dialog`

CHANGELOG.md, package-lock.json, package.json, src/hooks.ts, test-e2e/features/dialog.feature
=> fixed `reuseSession` flag

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts, test-e2e/features/dialog.feature, test-e2e/features/pageObject.feature, test-e2e/page_object/index.ts
=> Added capability to provide _defaultResolver_ to define default logic to identify element

CHANGELOG.md, package-lock.json, package.json, src/pageObject.ts
=> improved logging to show resolved selectors

.github/workflows/pull-request.yml, CHANGELOG.md, package-lock.json, package.json
=> updated dependencies

CHANGELOG.md, package.json, src/pageObject.ts
=> improved logging to display full path

.github/workflows/pull-request.yml, package-lock.json, package.json, src/actions.ts, src/cookies.ts, src/dialog.ts, src/execute.ts, src/hooks.ts, src/intercept.ts, src/keyboardActions.ts, src/localSessionStorage.ts, src/memory.ts, src/mobile.ts, src/mock.ts, src/mouseActions.ts, src/poDefine.ts, src/types.ts, src/validations.ts, src/waits.ts, test-e2e/page_object/index.ts, test-e2e/step-definitions/index.ts
=> updated imports to @qavajs/core

package-lock.json, package.json, src/actions.ts, src/memory.ts, src/validations.ts, test-e2e/features/actions.feature
=> added into to type steps

src/QavajsWdioWorld.ts
=> fixed element type in wdio world
